name: "Build and Push Docker Image"
on:
    workflow_dispatch:

# build and push container image to dockerhub:
# https://hub.docker.com/repository/docker/isepdei/juice-shop
#
# uses org secrets: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN

env:
  CYCLONEDX_NPM_VERSION: '^1.12.0'
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # get repo code
      - name: "Check out Git repository"
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
      # setup QEMU; this is needed to build containers for different platforms 
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 #v3.0.0
      # setup buildx; this is what actually lets us build containers for different platforms 
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 #v3.0.0        
      # auth against dockerhub user defined secrets (required getting an access token from docker hub)
      - name: "Login to DockerHub"
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d #v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # setup env variables used for image version
      - name: "Set tag & labels for ${{ github.ref }}"
        run: |
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
          echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
          echo "BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”`" >> $GITHUB_ENV
      # build image and send to dockerhub; key 'platforms' uses buildx to let us build for more platforms
      - name: "Build and push image"
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 #v5.1.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64 # could have more, e.g. linux/amd64,linux/arm64         
          push: true
          tags: |
            isepdei/juice-shop:${{ env.DOCKER_TAG }}
          build-args: |
            VCS_REF=${{ env.VCS_REF }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            CYCLONEDX_NPM_VERSION=${{ env.CYCLONEDX_NPM_VERSION }}
